# This is a basic workflow to help you get started with Actions

name: Build Tailwind

# Controls when the workflow will run
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Get dependencies with NPM
        run: npm ci
      - name: Get PostCSS Styles
        run: npm run tailwind:build

      - uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: "Build with PostCSS"
